services:
  # Backend Service
  - type: web
    name: inventory-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
    # IMPORTANT: You MUST add your MongoDB connection string in Render Dashboard
    # Go to your service -> Environment -> Add MONGODB_URI with your MongoDB Atlas connection string

  # Frontend Service  
  - type: web
    name: inventory-frontend
    env: node
    plan: free
    buildCommand: cd frontend && npm install
    startCommand: cd frontend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    # Update API endpoints in your frontend to point to the backend service
    # The backend will be available at: https://inventory-backend.onrender.com