services:
  - type: web
    name: inventory-management
    runtime: node
    buildCommand: npm run install:all && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        fromDatabase:
          name: inventory-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 4000
      - key: CLIENT_URL
        fromService:
          type: web
          name: inventory-management
          property: url