services:
  # Backend Service
  - type: web
    name: inventory-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    # Add your environment variables here
    # - key: MONGODB_URI
    #   value: your_mongodb_connection_string
    # - key: JWT_SECRET
    #   value: your_jwt_secret

  # Frontend Service  
  - type: web
    name: inventory-frontend
    env: node
    plan: free
    rootDir: frontend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    # Update API endpoints in your frontend to point to the backend service
    # The backend will be available at: https://inventory-backend.onrender.com